/**:
  ros__parameters:
    min_longitudinal_offset: 0.018
    max_longitudinal_offset: 0.032
    min_lateral_offset: -0.014
    max_lateral_offset: 0.014
    min_height_offset: 0.008
    max_height_offset: 0.015