/**:
  ros__parameters:
    wheel_radius: 0.396 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.06 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.515 # between front wheel center and rear wheel center
    wheel_tread: 0.533 # between left wheel center and right wheel center
    front_overhang: 0.12 # between front wheel center and vehicle front
    rear_overhang: 0.25 # between rear wheel center and vehicle rear
    left_overhang: 0.04 # between left wheel center and vehicle left
    right_overhang: 0.04 # between right wheel center and vehicle right
    vehicle_height: 0.37
    max_steer_angle: 1.0472 # [rad]
